// <auto-generated />
using System;
using ExamRegistration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamRegistration.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230106091427_Add_column_Subject_SubjectCode")]
    partial class Add_column_Subject_SubjectCode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("ExamRegistration.Models.Subject", b =>
                {
                    b.Property<Guid>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("ExamRegistration.Models.SubjectGroup", b =>
                {
                    b.Property<Guid>("SubjectGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectGroupName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectGroupID");

                    b.HasIndex("SubjectID");

                    b.ToTable("SubjectGroup");
                });

            modelBuilder.Entity("ExamRegistration.Models.SubjectGroup", b =>
                {
                    b.HasOne("ExamRegistration.Models.Subject", "Subject")
                        .WithMany("SubjectGroup")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ExamRegistration.Models.Subject", b =>
                {
                    b.Navigation("SubjectGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
